import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {GraphQLClient, gql} from 'graphql-request'
import Menu from './components/menu'
import BlogHeader from './components/blogHeader'
import BlogContainer from './components/blogContainer'
import Article from './components/article'


// 地址填入要调用的 api 地址
const client = new GraphQLClient('https://api-ap-northeast-1.hygraph.com/v2/cl88xvy281qi801tafuguf6v4/master')
const QUERY = gql`
	{
		posts{
			id,
			title,
			category,
			datePublished,
			description,
			content{
			  html
			},
			readTime,
			author{
			  name,
			  avatar{
				url
			  }
			},
			cover{
			  url
			}
		  }
	}
`

//👇 Nex.js 帮我们定义好的函数，用于获取数据
export async function getStaticProps(){
	//【解构赋值给】上面的【请求数据结构】
	const {posts} = await client.request(QUERY)

	return{
		props:{
			posts,//把 props 数据传递进来
		}
	}
}



export default function Home({posts}) {

console.log('posts',posts);

  return (
    <div className={styles.container}>
      <Head>
        <title> Zen Blog </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

	  {/* 🌟 内容分区 */}
	  <div className="blog">
			{/* 🌟 左侧菜单 */}
			<Menu />

			{/* 🌟 顶部标题 */}
			<BlogHeader />

		 	{/* 🌟【博客内容】:【数据回填】: 填入后端返回的数据(posts 变量) 并传递给【子组件】*/}
			<BlogContainer posts={posts}/>

			{/* 🌟 右侧列表 */}
			<Article />

	  </div>
    </div>
  )
}
